# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@3.0.0
  with:
    # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
    ftp-server: //pruebaseduardo.16mb.com/public_html/scaffolder
    # FTP account username
    ftp-username: u800399338
    # FTP account password
    ftp-password: tVfemg9C
    # The local folder to copy, defaults to root project folder
    local-dir: # optional
    # Passes through options into git-ftp
    git-ftp-args: # optional
